[AND-7122] Logout realm user
rockspoon/structure-poc pull request #6
Opened 2023-07-07 11:18 UTC by olegoreshenko

Task: https://rockspoon.atlassian.net/browse/AND-7122
- logout user

2023-07-07 14:04 UTC, tinenbruno approved these changes

2023-07-10 12:06 UTC, allan-rockspoon requested changes

2023-07-10 12:06 UTC, allan-rockspoon commented on app/poc/src/main/java/com/example/poc/domain/ObserveUserLoggedInUseCase.kt
> +class ObserveUserLoggedInUseCase(
If it's just for observer a model you can inject the repository direct, but it's okay.

2023-07-10 12:06 UTC, allan-rockspoon commented on datasource/streaming_realm/src/main/java/com/example/poc/datasource/streaming_realm/RealmDatabase.kt
> +        withTimeout(2000) {
There is no other way to do this? Maybe using realmApp.authenticationChangeAsFlow()?

2023-07-10 12:13 UTC, olegoreshenko commented on datasource/streaming_realm/src/main/java/com/example/poc/datasource/streaming_realm/RealmDatabase.kt
> +        withTimeout(2000) {
I tried using authenticationChangeAsFlow, but it didn't work for me. When user logged out, no events were in this flow.

2023-07-13 13:54 UTC, KirillChalenko commented on core/data/src/main/java/com/example/poc/core/data/credentials/CredentialsRepository.kt
> +    suspend fun logout() {
why do you need a separate method for logout? Wasn't deleteCredentials() created for that purpose?

2023-07-13 13:55 UTC, KirillChalenko commented on core/data/src/main/java/com/example/poc/core/data/credentials/CredentialsRealmDataSourceImpl.kt
> +    override suspend fun logout() {
```suggestion
    override suspend fun deleteCredentials() {
```

2023-07-13 13:57 UTC, KirillChalenko commented on feature/settings/src/main/java/com/example/poc/settings/domain/LogoutUserUseCase.kt
> +class LogoutUserUseCase(private val credentialsRepository: CredentialsRepository) {
the class looks useless

2023-07-13 14:23 UTC, olegoreshenko commented on core/data/src/main/java/com/example/poc/core/data/credentials/CredentialsRealmDataSourceImpl.kt
> +    override suspend fun logout() {
CredentialsRealmDataSourceImpl is confusing for me. It doesn't save or store anything. It just initialize Realm with credentials. Also, when we call delete, it doesn't delete, it logs out user. Maybe we should remove this DataSource and call it from usecase ?

2023-07-14 08:17 UTC, allan-rockspoon approved these changes

2023-07-14 08:17 UTC, allan-rockspoon commented on core/data/src/main/java/com/example/poc/core/data/credentials/CredentialsRealmDataSourceImpl.kt
> +    override suspend fun logout() {
It doesn't store directly, but Realm keeps the credentials inside it for every sync call.

2023-07-14 08:17 UTC, allan-rockspoon commented on core/data/src/main/java/com/example/poc/core/data/credentials/CredentialsRepository.kt
> +    suspend fun logout() {
deleteCredentials should also delete the credentials on the Realm data source (i.e.: logout on Realm).

2023-07-14 08:17 UTC, allan-rockspoon commented on feature/settings/src/main/java/com/example/poc/settings/domain/LogoutUserUseCase.kt
> +class LogoutUserUseCase(private val credentialsRepository: CredentialsRepository) {
Not really necessary. Use case here is optional, it's preferable just inject the repository directly.

2023-07-14 08:20 UTC, merged